### ISSUE TITLE
Folder issue

### ISSUE THREAD

**Issue by cagnulein** [bw4sz/OpenCV_HummingbirdsMotion#29]
Hi man, great work with this program!
I think i hit a issue: every time i try to run a batch on a folder gives me this error:
Traceback (most recent call last):
  File "<string>", line 113, in worker
  File "kivy\properties.pyx", line 408, in kivy.properties.Property.__set__ (kivy\properties.c:5114)
  File "kivy\properties.pyx", line 446, in kivy.properties.Property.set (kivy\properties.c:5876)
  File "kivy\properties.pyx", line 501, in kivy.properties.Property.dispatch (kivy\properties.c:6557)
  File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
  File "kivy\_event.pyx", line 1106, in kivy._event.EventObservers._dispatch (kivy\_event.c:12301)
  File "site-packages\kivy\lang.py", line 1557, in custom_callback
  File ".\motionmeerkat.kv", line 247, in <module>
    on_waitflag: if self.waitflag==1: root.gotoresults(app.root)
  File "<string>", line 124, in gotoresults
  File "site-packages\kivy\uix\relativelayout.py", line 255, in __init__
  File "site-packages\kivy\uix\floatlayout.py", line 65, in __init__
  File "site-packages\kivy\uix\layout.py", line 72, in __init__
  File "site-packages\kivy\uix\widget.py", line 320, in __init__
  File "site-packages\kivy\lang.py", line 1970, in apply
  File "site-packages\kivy\lang.py", line 2130, in _apply_rule
BuilderException: Parser: File ".\motionmeerkat.kv", line 295:
...
    293:            font_size:20
    294:        Label:
>>  295:            text: "[b]Run time:[/b] " + str(round(app.root.motionVid.total_min,2)) + " min"
    296:            markup: True
    297:            font_size:20
...
BuilderException: Parser: File ".\motionmeerkat.kv", line 295:
...
    293:            font_size:20
    294:        Label:
>>  295:            text: "[b]Run time:[/b] " + str(round(app.root.motionVid.total_min,2)) + " min"
    296:            markup: True
    297:            font_size:20
...
AttributeError: Motion instance has no attribute 'total_min'
  File "site-packages\kivy\lang.py", line 1742, in create_handler
  File ".\motionmeerkat.kv", line 295, in <module>
    text: "[b]Run time:[/b] " + str(round(app.root.motionVid.total_min,2)) + " min"

  File "site-packages\kivy\lang.py", line 2115, in _apply_rule
  File "site-packages\kivy\lang.py", line 1747, in create_handler

Everything works fine if i set a single file each time.
Let me know
Roberto

**Comment by bw4sz** [comment]
I'll have a look, thanks.

**Comment by bw4sz** [comment]
Okay, i can begin by confirming this does not happen through the GUI, use that until i figure out why there is a difference, it should be very minor.

**Comment by cagnulein** [comment]
Thanks but it happens through the GUI to me :S 
I'm using the last installer for windows

**Comment by bw4sz** [comment]
hmm, can't recreate here, let me reinstall on a clean system and see. I made a bunch of files in a folder, and ran in batch mode fine. I'll get to the bottom of it. Thanks.

**Comment by bw4sz** [comment]
Can you tell me anything else you are setting that might create a conflict. I made a folder on my desktop with two videos, and ran in batch mode, no problem.

![image](https://cloud.githubusercontent.com/assets/1208492/17348848/5e689ff8-58ce-11e6-8a7f-5e879c38622b.png)

yields the final screen for the final file

![image](https://cloud.githubusercontent.com/assets/1208492/17348864/77836c8e-58ce-11e6-8ffa-c814ae2aaf68.png)

**Comment by cagnulein** [comment]
I will send you a video, now i have no time to reproduce the issue :(

**Comment by bw4sz** [comment]
Take your time. I'm closing this issue, I will reopen when i can recreate the error. All feedback welcome on how to program can be improved.

**Comment by cagnulein** [comment]
I understood the issue and it was very simple :) You don't support .MOV file, isn't it?
Anyway i forked it and i add it to the if statement and it worked without any other changes.
That's all :)

**Comment by bw4sz** [comment]
got it. will add to next version.
