### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yasuni305** [bw4sz/OpenCV_HummingbirdsMotion#48]
Traceback (most recent call last):
  File "<string>", line 131, in worker
  File "MotionMeerkat\motionClass.py", line 825, in wrap
  File "MotionMeerkat\motionClass.py", line 187, in prep
IndexError: list index out of range

**Comment by bw4sz** [comment]
Please follow the instructions. I'm happy to help, but I need alot more context. What kind of video was this run on? Operating system? When did you download? Si prefieres espanol (yasuni como el parque en Ecuador?), esta bien conmigo.

**Comment by yasuni305** [comment]
Gracias es más comodo para mí

 Bueno el tipo de video es .AVI, en windows y descargue el programa la anterior semana, la version 2.0.5.

________________________________
De: Ben Weinstein <notifications@github.com>
Enviado: miércoles, 07 de junio de 2017 13:56:10
Para: bw4sz/OpenCV_HummingbirdsMotion
Cc: yasuni305; Author
Asunto: Re: [bw4sz/OpenCV_HummingbirdsMotion] error (#48)


Please follow the instructions. I'm happy to help, but I need alot more context. What kind of video was this run on? Operating system? When did you download? Si prefieres espanol (yasuni como el parque en Ecuador?), esta bien conmigo.

**Comment by yasuni305** [comment]
Justo son dos especies de Yasuní de las que estoy estudiando los sindromes y sistema de polinización, deje las camaras trampa por 6 días.

________________________________
De: Andres eduardo Melo Burbano <andreseduardo1992@hotmail.es>
Enviado: miércoles, 07 de junio de 2017 15:35:16
Para: bw4sz/OpenCV_HummingbirdsMotion
Asunto: Re: [bw4sz/OpenCV_HummingbirdsMotion] error (#48)


Gracias es más comodo para mí

 Bueno el tipo de video es .AVI, en windows y descargue el programa la anterior semana, la version 2.0.5.

________________________________
De: Ben Weinstein <notifications@github.com>
Enviado: miércoles, 07 de junio de 2017 13:56:10
Para: bw4sz/OpenCV_HummingbirdsMotion
Cc: yasuni305; Author
Asunto: Re: [bw4sz/OpenCV_HummingbirdsMotion] error (#48)


Please follow the instructions. I'm happy to help, but I need alot more context. What kind of video was this run on? Operating system? When did you download? Si prefieres espanol (yasuni como el parque en Ecuador?), esta bien conmigo.

**Comment by yasuni305** [comment]
Disculpa fueron por 3 días

________________________________
De: Andres eduardo Melo Burbano <andreseduardo1992@hotmail.es>
Enviado: miércoles, 07 de junio de 2017 15:37:06
Para: bw4sz/OpenCV_HummingbirdsMotion
Asunto: Re: [bw4sz/OpenCV_HummingbirdsMotion] error (#48)


Justo son dos especies de Yasuní de las que estoy estudiando los sindromes y sistema de polinización, deje las camaras trampa por 6 días.

________________________________
De: Andres eduardo Melo Burbano <andreseduardo1992@hotmail.es>
Enviado: miércoles, 07 de junio de 2017 15:35:16
Para: bw4sz/OpenCV_HummingbirdsMotion
Asunto: Re: [bw4sz/OpenCV_HummingbirdsMotion] error (#48)


Gracias es más comodo para mí

 Bueno el tipo de video es .AVI, en windows y descargue el programa la anterior semana, la version 2.0.5.

________________________________
De: Ben Weinstein <notifications@github.com>
Enviado: miércoles, 07 de junio de 2017 13:56:10
Para: bw4sz/OpenCV_HummingbirdsMotion
Cc: yasuni305; Author
Asunto: Re: [bw4sz/OpenCV_HummingbirdsMotion] error (#48)


Please follow the instructions. I'm happy to help, but I need alot more context. What kind of video was this run on? Operating system? When did you download? Si prefieres espanol (yasuni como el parque en Ecuador?), esta bien conmigo.
