### ISSUE TITLE
an integer is required

### ISSUE THREAD

**Issue by GrettelSalguero** [bw4sz/OpenCV_HummingbirdsMotion#50]
Im traying to use the program for detect hummingbirds motion and it returnds this error: 

Traceback (most recent call last):
  File "<string>", line 131, in worker
  File "MotionMeerkat\motionClass.py", line 825, in wrap
  File "MotionMeerkat\motionClass.py", line 128, in prep
TypeError: an integer is required

**Comment by bw4sz** [comment]
Can you send me the parameter file. First test the default. Open up MotionMeerkat and just hit run. Does everything work properly?

**Comment by GrettelSalguero** [comment]
Hi, Ben. 

Thank you a lot for your for your quick response. I change the address of the input file to a folder with a single video file and it worked for me. 
I do not know if that is always necessary?. 

The analysis time of my videos is very big. Possibly because of its resolution. What is the recommended resolution or file size? Will it be faster in another format? At this time the analysis takes between 30 and 50 minutes. This is not profitable for me because the total time of each video is only 10 minutes.

 Thanks for your help

Grettel.
